### ISSUE TITLE
Power Management

### ISSUE THREAD

**Issue by mikeshams** [varshini15reddy/Capstone-project_G5#10]
1. How to manage the power consumption for the MCU in terms of software?
2. Revise your ppt file accordingly!
3. Demonstrate your task accordingly!

**Comment by Rakshithanagapuri97** [comment]
The power consumption in raspberry pi 3B is it goes into on mode as it is provided with power supply. The modes of on or off mode depends on raspberry pi we are using .
[edited reeta.pptx](https://github.com/varshini15reddy/Capstone-project_G5/files/6933494/edited.reeta.pptx)
