### ISSUE TITLE
Testing Components

### ISSUE THREAD

**Issue by mikeshams** [varshini15reddy/Capstone-project_G5#5]
you need to demonstrate testing the GPS Module successfully

**Comment by vamshi1285** [comment]
As a task issue, we tried to test the GPS module multiple times  but it is not giving up an accurate result

**Comment by mikeshams** [comment]
see if the wires are loose or the Internet is unstable

**Comment by vamshi1285** [comment]
we will try testing  it again by soldering the connections and using a different breadboard, if even that fails we will do it with the new component

**Comment by vamshi1285** [comment]
we have come to a conclusion that we are testing with a faulty GPS module, so we ordered a new component and will be receiving it by Friday

**Comment by vamshi1285** [comment]
I have successfully tested the GPS module with Arduino, I am attaching the output link for your reference 
https://youtube.com/shorts/Q9btYSfDAmE?feature
