### ISSUE TITLE
Schematic Capture Design

### ISSUE THREAD

**Issue by mikeshams** [varshini15reddy/Capstone-project_G5#6]
1. You need to demonstrate how to create the schematic capture by yourself today
2. Explain about limitations with Easy EDA
3. Explain about DRC

**Comment by SaiSwethan** [comment]
2 .  EasyEDA Supports PCB export to the 3D model file. Exporting the OBJ format is currently supported. Currently creating EDA OBJ format is not the standard OBJ format, which contains the material data. The need to separate the material data can be in Win10 with the 3D viewer with color. You can use the following gadget to split the obj material file, and the split will result in an MTL and OBJ file. The split file can be opened in other 3D software and converted to other formats.

3 . A design rule check (DRC) is simply a set of rules a designer can use to ensure their schematic matches all the dimensional tolerances and manufacturing considerations they set for a board. A DRC lets you verify that your schematic and layout in fact reflects the design margins you wished to incorporate in your design. When one of these design margins is violated, the DRC tool will let you know by flagging the missing PIN, miswire, short or other error on your schematic or layout.
