### ISSUE TITLE
Temperature and Humidity Sensor Interfacing

### ISSUE THREAD

**Issue by mikeshams** [varshini15reddy/Capstone-project_G5#7]
1. What is the unit for the humidity output results and what do they mean?
2. What is the communication protocol between your sensor and the Arduino? Which line in your code confirms that?

**Comment by vamshi1285** [comment]
humidity describes the water content of air and is expressed in either gram per cubic meter or grams per kilogram. Relative humidity, expressed as a percentage, indicates a present state of absolute humidity relative to a maximum humidity given the same temperature.

**Comment by vamshi1285** [comment]
no communication protocal will be used between arduino and dht
A Digital Pin is used for the task.
