### ISSUE TITLE
Metal Detector Interfacing

### ISSUE THREAD

**Issue by mikeshams** [varshini15reddy/Capstone-project_G5#8]
1. Revise your references based on APA style!
2. Review your code and add comments to each line carefully! Do you need all those lines?

**Comment by Rakshithanagapuri97** [comment]
stdio.h standard library is used to define 3 types of variables, several macros and functions for performing input and output.
string.h standard library is used to define predefined functions designed to handle strings.
errno.h standard library is used to define macros for reporting and retrieving error conditions or error number.
stdlib.h standard library is used to define the memory allocation, process control,conversions.
all the lines are used to perform the above functions .
[first ppt (1).pptx](https://github.com/varshini15reddy/Capstone-project_G5/files/6827465/first.ppt.1.pptx)

**Comment by Rakshithanagapuri97** [comment]
all the libraries are discussed and ppt is updated with references.
